param(
  [string]$Root = ".\bench-data\tpcds",
  [double]$ScaleFactor = 1.0,
  [switch]$ParquetOnly,
  [switch]$IcebergOnly,
  [switch]$FreshWarehouse
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$rootDir = [System.IO.Path]::GetFullPath((Join-Path $repoRoot $Root))
$parquetRoot = Join-Path $rootDir "parquet"
$warehouseRoot = Join-Path $rootDir "warehouse"
$duckdbFile = Join-Path $rootDir "tpcds-gen.duckdb"
$defaultWinutilsHome = "C:\Developer\winutils"

function Invoke-Step([string]$Label, [scriptblock]$Script) {
  Write-Host $Label
  & $Script
  if ($LASTEXITCODE -ne 0) {
    throw "$Label failed (exit code $LASTEXITCODE)."
  }
}

New-Item -ItemType Directory -Force -Path $rootDir | Out-Null
New-Item -ItemType Directory -Force -Path $parquetRoot | Out-Null
New-Item -ItemType Directory -Force -Path $warehouseRoot | Out-Null
if (Test-Path $duckdbFile) {
  Remove-Item -Force $duckdbFile
}

if (-not $IcebergOnly) {
  Invoke-Step "Installing Python deps (duckdb, pyspark)..." {
    python -m pip install --upgrade pip
  }
  Invoke-Step "Installing Python deps (duckdb, pyspark 3.5.x)..." {
    python -m pip install --upgrade duckdb "pyspark==3.5.3"
  }

  Invoke-Step "Generating TPC-DS parquet (sf=$ScaleFactor)..." {
    python (Join-Path $repoRoot "scripts\generate-tpcds-parquet.py") `
      --out $parquetRoot `
      --sf $ScaleFactor `
      --duckdb-file $duckdbFile
  }
} else {
  Write-Host "Skipping parquet generation (--IcebergOnly)."
}

if (-not $ParquetOnly) {
  $freshArg = @()
  if ($FreshWarehouse) {
    $freshArg = @("--fresh")
  }
  if (-not $env:HADOOP_HOME -and (Test-Path $defaultWinutilsHome)) {
    $env:HADOOP_HOME = $defaultWinutilsHome
  }
  if (-not $env:hadoop_home_dir -and $env:HADOOP_HOME) {
    $env:hadoop_home_dir = $env:HADOOP_HOME
  }

  Invoke-Step "Building Iceberg warehouse from parquet..." {
    python (Join-Path $repoRoot "scripts\build-iceberg-warehouse.py") `
      --parquet-root $parquetRoot `
      --warehouse-root $warehouseRoot `
      --catalog local `
      --schema tpcds `
      --driver-memory 8g `
      @freshArg
  }
} else {
  Write-Host "Skipping Iceberg warehouse build (--ParquetOnly)."
}

$benchYaml = Join-Path $repoRoot "benchmarks\tpcds\bench.yaml"
$warehouseForYaml = ($warehouseRoot -replace '\\', '/')
$parquetForYaml = ($parquetRoot -replace '\\', '/')
@"
# Auto-generated by scripts/setup-local-tpcds.ps1

warehouse: $warehouseForYaml
catalog: local
schema: tpcds

manifest: benchmarks/tpcds/manifest.toml
iterations: 1
warmup: true

duckdb:
  parquet_root: $parquetForYaml
  schema: tpcds
"@ | Set-Content -Path $benchYaml -Encoding utf8

Write-Host ""
if ($ParquetOnly) {
  Write-Host "Parquet setup complete."
} else {
  Write-Host "Setup complete."
}
Write-Host "parquet_root  : $parquetRoot"
if (-not $ParquetOnly) {
  Write-Host "warehouse_root: $warehouseRoot"
}
Write-Host ""
Write-Host "Next:"
Write-Host "  1) Edit benchmarks\tpcds\bench.yaml:"
Write-Host "     - warehouse: $warehouseRoot"
Write-Host "     - duckdb.parquet_root: $parquetRoot"
Write-Host "  2) Run benchmark:"
Write-Host "     cargo run -p idb-bench --release -- --config benchmarks/tpcds/bench.yaml"
Write-Host ""
Write-Host "Scale factor 10 example:"
Write-Host "  .\scripts\setup-local-tpcds.ps1 -Root .\bench-data\tpcds-sf10 -ScaleFactor 10 -FreshWarehouse"
Write-Host "Retry iceberg only (parquet already generated):"
Write-Host "  .\scripts\setup-local-tpcds.ps1 -Root .\bench-data\tpcds-sf10 -IcebergOnly -FreshWarehouse"
